### ISSUE TITLE
Tiến độ bài tập

### ISSUE THREAD

**Issue by huong1999** [viethahn94/baiTapHuong#8]
Tuần này anh vẫn tiếp tục làm bài nhé.
Các bài trước em đã check xong. Còn mấy bài khó nếu bí anh cứ hỏi thêm để hoàn thành hết bài tập.

**Comment by viethahn94** [comment]
Oki. A làm xong vài bài r mà chưa gửi. Lát nữa a gửi nốt rồi check cho a
nhé.

Việt Hà

Vào 9:30, Th 2, 13 thg 4, 2020 huong1999 <notifications@github.com> đã viết:
